[package]
name = "hello_rust"
version = "0.1.0"
edition = "2024"

[dependencies]
fs2 = "0.4"
chrono = "0.4"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
base64 = "0.22.1"
sha2 = "0.10"
hex = "0.4"
